#!/usr/bin/env bash
# One-time rig identity: unique worker id + ed25519 payout seed (persistent on disk install).
set -euo pipefail

ROOT="${HACKME_ROOT:-/opt/hackme}"
ENV_STATE="/var/lib/hackme/miner.env"
MARKER="/var/lib/hackme/.firstboot_done"
POOL_TOKEN_FILE="/etc/hackme/pool.token"

mkdir -p /var/lib/hackme
chmod 700 /var/lib/hackme

if [[ -f "$MARKER" && -f "$ENV_STATE" ]]; then
  exit 0
fi

HOST_ID="$(hostname -s 2>/dev/null | tr -cs 'a-zA-Z0-9-' '_' | cut -c1-24)"
RAND="$(openssl rand -hex 3 2>/dev/null || echo 000)"
WORKER_ID="worker-${HOST_ID}-${RAND}"

SEED_HEX=""
if [[ -x "${ROOT}/bin/minersign" ]] && command -v jq >/dev/null 2>&1; then
  SEED_HEX="$("${ROOT}/bin/minersign" -gen-seed 2>/dev/null | jq -r '.HACKME_MINER_ED25519_SEED_HEX // .miner_seed_hex // empty')"
fi
if [[ -z "$SEED_HEX" ]]; then
  SEED_HEX="$(openssl rand -hex 32)"
fi

COORD_URL="${COORD_URL:-https://hackme.tech/pool/coordinator}"
POOL_TOKEN=""
[[ -f "$POOL_TOKEN_FILE" ]] && POOL_TOKEN="$(tr -d '\r\n' <"$POOL_TOKEN_FILE")"

cat >"$ENV_STATE" <<EOF
# Generated by hackme-miner-firstboot on $(date -u +%Y-%m-%dT%H:%M:%SZ)
WORKER_ID=${WORKER_ID}
COORD_URL=${COORD_URL}
COORD_TOKEN=${POOL_TOKEN}
HACKME_MINER_ED25519_SEED_HEX=${SEED_HEX}
BATCH_SIZE=4194304
GPU_CHUNK=4194304
SEARCH_TIMEOUT_MS=12000
HACKME_GPU_BACKEND=auto
HACKME_DESKTOP_GPU_POOL=1
EOF
chmod 600 "$ENV_STATE"
touch "$MARKER"
chmod 600 "$MARKER"

echo "[hackme-miner-firstboot] worker_id=${WORKER_ID} env=${ENV_STATE}"
if command -v systemctl >/dev/null 2>&1; then
  systemctl restart hackme-miner-worker.service 2>/dev/null || true
fi
