#!/usr/bin/env bash
# One-time rig identity: worker id + ed25519 seed (skipped when Zero-Knowledge Start already wrote env).
set -uo pipefail

ROOT="${HACKME_ROOT:-/opt/hackme}"
ENV_STATE="/var/lib/hackme/miner.env"
MARKER="/var/lib/hackme/.firstboot_done"
POOL_TOKEN_FILE="/etc/hackme/pool.token"

mkdir -p /var/lib/hackme
chmod 700 /var/lib/hackme

if [[ -f "$MARKER" ]]; then
  exit 0
fi

# Zero-Knowledge / init-worker already provisioned signing material.
if [[ -f "$ENV_STATE" ]] && grep -q '^HACKME_MINER_ED25519_SEED_HEX=' "$ENV_STATE" 2>/dev/null; then
  if ! grep -q '^WORKER_ID=' "$ENV_STATE" 2>/dev/null; then
    HOST_ID="$(hostname -s 2>/dev/null | tr -cs 'a-zA-Z0-9-' '_' | cut -c1-24)"
    echo "WORKER_ID=worker-${HOST_ID}-$(openssl rand -hex 3 2>/dev/null || echo 000)" >>"$ENV_STATE"
  fi
  if [[ -f "$POOL_TOKEN_FILE" ]] && ! grep -q '^COORD_TOKEN=' "$ENV_STATE" 2>/dev/null; then
    echo "COORD_TOKEN=$(tr -d '\r\n' <"$POOL_TOKEN_FILE")" >>"$ENV_STATE"
  fi
  touch "$MARKER"
  chmod 600 "$MARKER"
  echo "[hackme-miner-firstboot] skip — seed present (ZK or prior init)"
  exit 0
fi

HOST_ID="$(hostname -s 2>/dev/null | tr -cs 'a-zA-Z0-9-' '_' | cut -c1-24)"
RAND="$(openssl rand -hex 3 2>/dev/null || echo 000)"
WORKER_ID="worker-${HOST_ID}-${RAND}"

SEED_HEX=""
if [[ -x "${ROOT}/bin/minersign" ]] && command -v jq >/dev/null 2>&1; then
  SEED_HEX="$("${ROOT}/bin/minersign" -gen-seed 2>/dev/null | jq -r '.HACKME_MINER_ED25519_SEED_HEX // .miner_seed_hex // empty')"
fi
if [[ -z "$SEED_HEX" ]]; then
  SEED_HEX="$(openssl rand -hex 32)"
fi

COORD_URL="${COORD_URL:-https://hackme.tech/pool/coordinator}"
POOL_TOKEN=""
[[ -f "$POOL_TOKEN_FILE" ]] && POOL_TOKEN="$(tr -d '\r\n' <"$POOL_TOKEN_FILE")"

PAYOUT_WALLET=""
[[ -f "$ENV_STATE" ]] && PAYOUT_WALLET="$(grep -E '^HACKME_PAYOUT_WALLET=' "$ENV_STATE" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '[:space:]')"

cat >"$ENV_STATE" <<EOF
# Generated by hackme-miner-firstboot on $(date -u +%Y-%m-%dT%H:%M:%SZ)
WORKER_ID=${WORKER_ID}
COORD_URL=${COORD_URL}
COORD_TOKEN=${POOL_TOKEN}
HACKME_MINER_ED25519_SEED_HEX=${SEED_HEX}
HACKME_PAYOUT_WALLET=${PAYOUT_WALLET}
BATCH_SIZE=16777216
GPU_CHUNK=4194304
SEARCH_TIMEOUT_MS=12000
HACKME_GPU_BACKEND=auto
HACKME_DESKTOP_GPU_POOL=1
HACKME_WORKER_CLAIM_COOLDOWN_MS=100
HACKME_WORKER_SIGN_SUBMITS=1
# Fleet default: PoH+fuzz hybrid (inline). Set =0 to disable dig.
HACKME_WORKER_HYBRID_FUZZ=1
HACKME_WORKER_HYBRID_FUZZ_MODE=inline
EOF
chmod 600 "$ENV_STATE"
touch "$MARKER"
chmod 600 "$MARKER"

echo "[hackme-miner-firstboot] worker_id=${WORKER_ID} env=${ENV_STATE}"
if command -v systemctl >/dev/null 2>&1; then
  systemctl restart hackme-miner-worker.service 2>/dev/null || true
fi
