#!/usr/bin/env bash
# HackMe OS worker init — safe hackme.ini parse OR Zero-Knowledge Start (auto wallet + recovery phrase).
# Never aborts boot; corrupt ini falls back to ZK generation when enabled.
set -uo pipefail

ROOT="${HACKME_ROOT:-/opt/hackme}"
OUT_ENV="${HACKME_INIT_ENV:-/var/lib/hackme/miner.env}"
DEFAULT_WALLET="${HACKME_OS_DEFAULT_WALLET:-HMC-719006d93916ad52}"
DEFAULT_POOL="${HACKME_OS_DEFAULT_POOL:-https://hackme.tech/pool/coordinator}"
LOG="${HACKME_INIT_LOG:-/var/log/hackme-init-worker.log}"
RUN_STATE="${HACKME_RUN_DIR:-/run/hackme-os}"
STATE_LIB="${HACKME_STATE_DIR:-/var/lib/hackme}"
ZK_JSON="${RUN_STATE}/zk-wallet.json"

mkdir -p "$(dirname "$OUT_ENV")" "$(dirname "$LOG")" "$RUN_STATE" "$STATE_LIB"
chmod 700 "$STATE_LIB" "$RUN_STATE" 2>/dev/null || true
log() { echo "[hackme-init] $*" | tee -a "$LOG"; }

# HMC- + 16 hex (consensus dev/treasury format)
valid_hmc() {
  local a="$1"
  [[ "$a" =~ ^HMC-[0-9a-fA-F]{16}$ ]]
}

sanitized_line() {
  local line="$1"
  line="${line//$'\r'/}"
  line="$(printf '%s' "$line" | tr -cd '[:print:]')"
  printf '%s' "$line"
}

resolve_ini_path() {
  local p
  for p in \
    "${HACKME_INI:-}" \
    "/var/lib/hackme/hackme.ini" \
    "/etc/hackme/hackme.ini" \
    "/boot/hackme.ini" \
    "/cdrom/hackme.ini" \
    "/media/hackme/hackme.ini"; do
    [[ -n "$p" && -f "$p" ]] && {
      printf '%s' "$p"
      return 0
    }
  done
  printf '%s' "${STATE_LIB}/hackme.ini"
}

ini_has_wallet_key() {
  local ini="$1"
  [[ -f "$ini" ]] || return 1
  grep -qiE '^[[:space:]]*(wallet|payout|miner_address|HACKME_WALLET)=' "$ini" 2>/dev/null
}

read_ini_wallet() {
  local ini="$1"
  local wallet=""
  if [[ ! -f "$ini" ]]; then
    return 1
  fi
  if command -v file >/dev/null 2>&1; then
    if ! file -b "$ini" 2>/dev/null | grep -qiE 'text|ascii|empty|ini'; then
      log "WARN: $ini looks binary — ignore wallet key"
      return 1
    fi
  elif grep -q $'\x00' "$ini" 2>/dev/null; then
    log "WARN: $ini contains NUL bytes — ignore wallet key"
    return 1
  fi
  while IFS= read -r raw || [[ -n "$raw" ]]; do
    local line
    line="$(sanitized_line "$raw")"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    case "$line" in
      wallet=*|payout=*|miner_address=*|HACKME_WALLET=*)
        local val="${line#*=}"
        val="$(printf '%s' "$val" | tr -d '[:space:]')"
        if valid_hmc "$val"; then
          wallet="$val"
        fi
        ;;
    esac
  done <"$ini"
  if [[ -n "$wallet" ]]; then
    printf '%s' "$wallet"
    return 0
  fi
  return 1
}

read_ini_pool() {
  local ini="$1"
  local pool="$DEFAULT_POOL"
  [[ -f "$ini" ]] || {
    printf '%s' "$pool"
    return 0
  }
  while IFS= read -r raw || [[ -n "$raw" ]]; do
    local line
    line="$(sanitized_line "$raw")"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    case "$line" in
      pool=*|coord=*|COORD_URL=*)
        local val="${line#*=}"
        val="$(printf '%s' "$val" | tr -d '[:space:]')"
        if [[ "$val" =~ ^https?:// ]]; then
          pool="$val"
        fi
        ;;
    esac
  done <"$ini"
  printf '%s' "$pool"
}

zk_enabled() {
  [[ "${HACKME_OS_ZERO_KNOWLEDGE:-1}" == "1" ]] || return 1
  [[ -x "${ROOT}/bin/minersign" ]] || return 1
  command -v jq >/dev/null 2>&1
}

generate_zk_wallet() {
  local json wallet seed phrase pubkey
  json="$("${ROOT}/bin/minersign" -gen-seed 2>/dev/null)" || return 1
  wallet="$(printf '%s' "$json" | jq -r '.miner_address_from_pubkey // empty')"
  seed="$(printf '%s' "$json" | jq -r '.HACKME_MINER_ED25519_SEED_HEX // .miner_seed_hex // empty')"
  phrase="$(printf '%s' "$json" | jq -r '.recovery_phrase // empty')"
  pubkey="$(printf '%s' "$json" | jq -r '.miner_pubkey_ed25519 // empty')"
  if ! valid_hmc "$wallet" || [[ ${#seed} -ne 64 ]]; then
    return 1
  fi
  printf '%s\n%s\n%s\n%s\n' "$wallet" "$seed" "$phrase" "$pubkey"
}

write_hackme_ini() {
  local ini="$1" wallet="$2" pool="$3"
  mkdir -p "$(dirname "$ini")"
  cat >"$ini" <<EOF
# HackMe OS — generated by Zero-Knowledge Start $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Leave wallet= empty on a fresh USB to auto-generate again (or set your HMC- address).
wallet=${wallet}
pool=${pool}
EOF
  chmod 600 "$ini"
}

INI="$(resolve_ini_path)"
POOL_URL="$(read_ini_pool "$INI")"
WALLET=""
SEED_HEX=""
RECOVERY_PHRASE=""
ZK_MODE=0

if w="$(read_ini_wallet "$INI" 2>/dev/null)"; then
  WALLET="$w"
  log "wallet from ini: $WALLET"
elif ini_has_wallet_key "$INI"; then
  log "WARN: ini has wallet key but invalid — fallback"
fi

if [[ -z "$WALLET" ]]; then
  if zk_enabled && gen="$(generate_zk_wallet 2>/dev/null)"; then
    WALLET="$(printf '%s' "$gen" | sed -n '1p')"
    SEED_HEX="$(printf '%s' "$gen" | sed -n '2p')"
    RECOVERY_PHRASE="$(printf '%s' "$gen" | sed -n '3p')"
    ZK_MODE=1
    write_hackme_ini "$INI" "$WALLET" "$POOL_URL"
    log "ZERO-KNOWLEDGE START: new wallet $WALLET → $INI"
    jq -nc \
      --arg wallet "$WALLET" \
      --arg phrase "$RECOVERY_PHRASE" \
      --arg ini_path "$INI" \
      --arg pool "$POOL_URL" \
      '{wallet:$wallet,recovery_phrase:$phrase,ini_path:$ini_path,pool:$pool}' >"$ZK_JSON"
    chmod 600 "$ZK_JSON"
    if [[ -n "$RECOVERY_PHRASE" ]]; then
      printf '%s\n' "$RECOVERY_PHRASE" >"${STATE_LIB}/recovery.phrase"
      chmod 600 "${STATE_LIB}/recovery.phrase"
    fi
    UI="${ROOT}/scripts/release/iso/hackme-os-ui.sh"
    if [[ -f "$UI" ]]; then
      # shellcheck source=hackme-os-ui.sh
      source "$UI"
      VER="$(grep -E '^VERSION_ID=' /etc/os-release 2>/dev/null | cut -d= -f2- | tr -d '"' || echo "$HACKME_UI_VERSION")"
      for tty in /dev/tty1 /dev/ttyS0 /dev/console; do
        [[ -w "$tty" ]] && hackme_ui_zk_tty_banner "$WALLET" "$RECOVERY_PHRASE" "$POOL_URL" "$VER" >"$tty" 2>/dev/null || true
      done
    fi
  else
    WALLET="$DEFAULT_WALLET"
    log "wallet default (fund): $WALLET"
  fi
fi

HOST_ID="$(hostname -s 2>/dev/null | tr -cs 'a-zA-Z0-9-' '_' | cut -c1-24)"
WORKER_ID="worker-${HOST_ID}-$(openssl rand -hex 2 2>/dev/null || echo 00)"

{
  echo "# init-worker.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "HACKME_PAYOUT_WALLET=$WALLET"
  echo "COORD_URL=$POOL_URL"
  echo "WORKER_ID=$WORKER_ID"
  echo "HACKME_OS_INIT=1"
  if [[ "$ZK_MODE" == "1" ]]; then
    echo "HACKME_OS_ZERO_KNOWLEDGE=1"
    echo "HACKME_MINER_ED25519_SEED_HEX=$SEED_HEX"
    echo "HACKME_WORKER_SIGN_SUBMITS=1"
    echo "BATCH_SIZE=16777216"
    echo "GPU_CHUNK=4194304"
    echo "SEARCH_TIMEOUT_MS=12000"
    echo "HACKME_WORKER_CLAIM_COOLDOWN_MS=100"
    echo "HACKME_GPU_BACKEND=auto"
    echo "HACKME_DESKTOP_GPU_POOL=1"
  fi
  if [[ -f /etc/hackme/pool.token ]]; then
    echo "COORD_TOKEN=$(tr -d '\r\n' </etc/hackme/pool.token)"
  fi
} >"$OUT_ENV"
chmod 600 "$OUT_ENV"

if [[ "$ZK_MODE" == "1" ]] && command -v systemctl >/dev/null 2>&1; then
  systemctl start hackme-zk-display.service 2>/dev/null || true
fi

log "init OK env=$OUT_ENV pool=$POOL_URL zk=$ZK_MODE"
exit 0
