#!/usr/bin/env bash
# Install compilers for POST /api/tasks/from_code (rust, c, cpp, tinygo, zig, assemblyscript, wat).
#
# Modes:
#   --desktop     — repo dev: $ROOT/logs/desktop/toolchains + .hackme-toolchains.env
#   --prefix PATH — custom install root (default: auto)
#   --system      — apt packages when root (VPS); also runs user/portable installs
#   --check-only  — print status and exit 0 if all present
#
# Usage (developer desktop):
#   bash scripts/ops/install_from_code_toolchains.sh --desktop
#
# Usage (VPS, root):
#   sudo bash scripts/ops/install_from_code_toolchains.sh --system --prefix /opt/hackme
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ZIG_VERSION="${ZIG_VERSION:-0.14.0}"
TINYGO_VERSION="${TINYGO_VERSION:-0.35.0}"
WABT_VERSION="${WABT_VERSION:-1.0.36}"
NODE_VERSION="${NODE_VERSION:-22.15.1}"
MODE_DESKTOP=0
MODE_SYSTEM=0
CHECK_ONLY=0
HACKME_PREFIX=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --desktop) MODE_DESKTOP=1; shift ;;
    --system) MODE_SYSTEM=1; shift ;;
    --check-only) CHECK_ONLY=1; shift ;;
    --prefix) HACKME_PREFIX="${2:-}"; shift 2 ;;
    *) echo "[toolchains] unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$HACKME_PREFIX" ]]; then
  if [[ "$MODE_DESKTOP" == "1" ]]; then
    HACKME_PREFIX="${HACKME_PREFIX:-$ROOT_DIR/logs/desktop/toolchains}"
  elif [[ "$(id -u)" -eq 0 ]] || [[ "$MODE_SYSTEM" == "1" ]]; then
    HACKME_PREFIX="${HACKME_PREFIX:-/opt/hackme}"
  else
    HACKME_PREFIX="${HACKME_PREFIX:-$HOME/.local/share/hackme/toolchains}"
  fi
fi

mkdir -p "$HACKME_PREFIX"

log() { echo "[toolchains] $*"; }
warn() { echo "[toolchains] WARN: $*" >&2; }

have() { command -v "$1" >/dev/null 2>&1; }

zig_portable_dir() {
  local arch
  arch="$(uname -m)"
  case "$arch" in
    x86_64) arch="x86_64" ;;
    aarch64|arm64) arch="aarch64" ;;
    *) arch="x86_64" ;;
  esac
  echo "$HACKME_PREFIX/zig-linux-${arch}-${ZIG_VERSION}"
}

export PATH="$HACKME_PREFIX/nodejs/bin:$HACKME_PREFIX/bin:$(zig_portable_dir):$HACKME_PREFIX/tinygo/bin:$HACKME_PREFIX/wabt/bin:${HACKME_PREFIX}/.cargo/bin:${HACKME_PREFIX}/.npm-global/bin:${PATH}"

write_env_file() {
  local envf="$1"
  local zig_dir
  zig_dir="$(zig_portable_dir)"
  local node_prefix=""
  if [[ -d "$HACKME_PREFIX/nodejs/bin" ]]; then
    node_prefix="${HACKME_PREFIX}/nodejs/bin:"
  fi
  cat >"$envf" <<EOF
# Generated by install_from_code_toolchains.sh — loaded by hackme node at startup
PATH=${node_prefix}${zig_dir}:${HACKME_PREFIX}/tinygo/bin:${HACKME_PREFIX}/wabt/bin:${HACKME_PREFIX}/bin:${HACKME_PREFIX}/.cargo/bin:${HACKME_PREFIX}/.npm-global/bin:/usr/local/bin:/usr/bin:/bin
RUSTUP_HOME=${HACKME_PREFIX}/.rustup
CARGO_HOME=${HACKME_PREFIX}/.cargo
NPM_CONFIG_PREFIX=${HACKME_PREFIX}/.npm-global
EOF
  chmod 644 "$envf" 2>/dev/null || true
}

link_bin() {
  local src="$1" name="$2"
  mkdir -p "$HACKME_PREFIX/bin"
  ln -sf "$src" "$HACKME_PREFIX/bin/$name"
}

install_zig_portable() {
  local zig_dir
  zig_dir="$(zig_portable_dir)"
  if [[ -x "$zig_dir/zig" ]]; then
    link_bin "$zig_dir/zig" zig
    return 0
  fi
  if [[ -d "$zig_dir" ]]; then
    warn "removing incomplete Zig tree at $zig_dir"
    rm -rf "$zig_dir"
  fi
  local arch tarball url tmp
  arch="$(uname -m)"
  case "$arch" in
    x86_64) arch="x86_64" ;;
    aarch64|arm64) arch="aarch64" ;;
    *) warn "unsupported arch for zig portable: $arch"; return 1 ;;
  esac
  tarball="zig-linux-${arch}-${ZIG_VERSION}.tar.xz"
  url="https://ziglang.org/download/${ZIG_VERSION}/${tarball}"
  tmp="$(mktemp -d)"
  log "downloading Zig ${ZIG_VERSION} (${arch})"
  curl -fL --connect-timeout 30 --max-time 900 -o "$tmp/$tarball" "$url"
  tar -xJf "$tmp/$tarball" -C "$tmp"
  rm -rf "$zig_dir"
  mv "$tmp/zig-linux-${arch}-${ZIG_VERSION}" "$zig_dir"
  rm -rf "$tmp"
  link_bin "$zig_dir/zig" zig
}

install_zig_apt_fallback() {
  if have zig; then
    link_bin "$(command -v zig)" zig
    return 0
  fi
  if [[ "$(id -u)" -eq 0 ]] && have apt-get; then
    log "apt: zig (fallback when portable download fails)"
    export DEBIAN_FRONTEND=noninteractive
    apt-get install -y -qq zig 2>/dev/null || return 1
    if have zig; then
      link_bin "$(command -v zig)" zig
      return 0
    fi
  fi
  return 1
}

install_tinygo_portable() {
  if [[ -x "$HACKME_PREFIX/tinygo/bin/tinygo" ]]; then
    link_bin "$HACKME_PREFIX/tinygo/bin/tinygo" tinygo
    return 0
  fi
  local arch tarball url tmp
  arch="$(uname -m)"
  case "$arch" in
    x86_64) arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    *) warn "unsupported arch for tinygo: $arch"; return 1 ;;
  esac
  tarball="tinygo${TINYGO_VERSION}.linux-${arch}.tar.gz"
  url="https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/${tarball}"
  tmp="$(mktemp -d)"
  log "downloading TinyGo ${TINYGO_VERSION}"
  curl -fsSL "$url" -o "$tmp/$tarball"
  tar -xzf "$tmp/$tarball" -C "$tmp"
  rm -rf "$HACKME_PREFIX/tinygo"
  mv "$tmp/tinygo" "$HACKME_PREFIX/tinygo"
  rm -rf "$tmp"
  link_bin "$HACKME_PREFIX/tinygo/bin/tinygo" tinygo
}

install_wabt_portable() {
  if [[ -x "$HACKME_PREFIX/wabt/bin/wat2wasm" ]]; then
    link_bin "$HACKME_PREFIX/wabt/bin/wat2wasm" wat2wasm
    return 0
  fi
  local arch tarball url tmp
  arch="$(uname -m)"
  case "$arch" in
    x86_64) arch="x86_64" ;;
    aarch64|arm64) arch="aarch64" ;;
    *) warn "unsupported arch for wabt: $arch"; return 1 ;;
  esac
  tarball="wabt-${WABT_VERSION}-ubuntu.tar.gz"
  url="https://github.com/WebAssembly/wabt/releases/download/${WABT_VERSION}/${tarball}"
  tmp="$(mktemp -d)"
  log "downloading WABT ${WABT_VERSION} (wat2wasm)"
  if ! curl -fsSL "$url" -o "$tmp/$tarball"; then
    warn "wabt download failed — try: sudo apt install wabt"
    rm -rf "$tmp"
    return 1
  fi
  tar -xzf "$tmp/$tarball" -C "$tmp"
  rm -rf "$HACKME_PREFIX/wabt"
  mkdir -p "$HACKME_PREFIX/wabt/bin"
  find "$tmp" -name wat2wasm -type f -executable 2>/dev/null | head -1 | while read -r bin; do
    install -m 755 "$bin" "$HACKME_PREFIX/wabt/bin/wat2wasm"
  done
  rm -rf "$tmp"
  if [[ -x "$HACKME_PREFIX/wabt/bin/wat2wasm" ]]; then
    link_bin "$HACKME_PREFIX/wabt/bin/wat2wasm" wat2wasm
  fi
}

install_node_portable() {
  if have npm; then
    return 0
  fi
  if [[ -x "$HACKME_PREFIX/nodejs/bin/npm" ]]; then
    link_bin "$HACKME_PREFIX/nodejs/bin/npm" npm
    link_bin "$HACKME_PREFIX/nodejs/bin/node" node
    return 0
  fi
  if ! have curl; then
    warn "curl required for portable Node.js"
    return 1
  fi
  local arch os_id tarball url tmp
  arch="$(uname -m)"
  case "$arch" in
    x86_64) arch="x64" ;;
    aarch64|arm64) arch="arm64" ;;
    *) warn "unsupported arch for portable node: $arch"; return 1 ;;
  esac
  os_id="linux"
  tarball="node-v${NODE_VERSION}-${os_id}-${arch}.tar.xz"
  url="https://nodejs.org/dist/v${NODE_VERSION}/${tarball}"
  tmp="$(mktemp -d)"
  log "downloading Node.js ${NODE_VERSION} (${os_id}-${arch}) for asc/npm"
  if ! curl -fsSL "$url" -o "$tmp/$tarball"; then
    warn "node download failed: $url"
    rm -rf "$tmp"
    return 1
  fi
  tar -xJf "$tmp/$tarball" -C "$tmp"
  rm -rf "$HACKME_PREFIX/nodejs"
  mv "$tmp/node-v${NODE_VERSION}-${os_id}-${arch}" "$HACKME_PREFIX/nodejs"
  rm -rf "$tmp"
  link_bin "$HACKME_PREFIX/nodejs/bin/node" node
  link_bin "$HACKME_PREFIX/nodejs/bin/npm" npm
}

install_rustup_user() {
  export CARGO_HOME="$HACKME_PREFIX/.cargo"
  export RUSTUP_HOME="$HACKME_PREFIX/.rustup"
  mkdir -p "$CARGO_HOME" "$RUSTUP_HOME"
  if [[ -x "$CARGO_HOME/bin/rustc" ]]; then
    link_bin "$CARGO_HOME/bin/rustc" rustc
    if [[ -x "$CARGO_HOME/bin/rustup" ]]; then
      env CARGO_HOME="$CARGO_HOME" RUSTUP_HOME="$RUSTUP_HOME" \
        "$CARGO_HOME/bin/rustup" target add wasm32-unknown-unknown >/dev/null 2>&1 || true
    fi
    return 0
  fi
  if ! have curl; then
    warn "curl required for rustup"
    return 1
  fi
  log "installing Rust via rustup (prefix $HACKME_PREFIX)"
  env CARGO_HOME="$CARGO_HOME" RUSTUP_HOME="$RUSTUP_HOME" HOME="$HACKME_PREFIX" \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    env CARGO_HOME="$CARGO_HOME" RUSTUP_HOME="$RUSTUP_HOME" HOME="$HACKME_PREFIX" \
      sh -s -- -y --no-modify-path --profile minimal
  if [[ -x "$CARGO_HOME/bin/rustup" ]]; then
    env CARGO_HOME="$CARGO_HOME" RUSTUP_HOME="$RUSTUP_HOME" \
      "$CARGO_HOME/bin/rustup" target add wasm32-unknown-unknown
  fi
  link_bin "$CARGO_HOME/bin/rustc" rustc
}

install_asc_npm() {
  export NPM_CONFIG_PREFIX="$HACKME_PREFIX/.npm-global"
  mkdir -p "$NPM_CONFIG_PREFIX"
  if [[ -x "$NPM_CONFIG_PREFIX/bin/asc" ]]; then
    link_bin "$NPM_CONFIG_PREFIX/bin/asc" asc
    return 0
  fi
  install_node_portable || true
  local npm_cmd="npm"
  if [[ -x "$HACKME_PREFIX/nodejs/bin/npm" ]]; then
    npm_cmd="$HACKME_PREFIX/nodejs/bin/npm"
  elif ! have npm; then
    warn "npm required for AssemblyScript (nodejs)"
    return 1
  fi
  log "npm install -g assemblyscript -> $NPM_CONFIG_PREFIX"
  "$npm_cmd" install -g assemblyscript@latest --prefix "$NPM_CONFIG_PREFIX" 2>/dev/null || \
    "$npm_cmd" install -g assemblyscript@latest
  if [[ -x "$NPM_CONFIG_PREFIX/bin/asc" ]]; then
    link_bin "$NPM_CONFIG_PREFIX/bin/asc" asc
  elif have asc; then
    true
  else
    return 1
  fi
}

install_system_apt() {
  [[ "$(id -u)" -eq 0 ]] || return 0
  if ! have apt-get; then
    return 0
  fi
  log "apt: clang, nodejs, npm, wabt, tinygo (best-effort)"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq curl ca-certificates xz-utils nodejs npm clang wabt 2>/dev/null || \
    apt-get install -y -qq curl ca-certificates xz-utils nodejs npm clang 2>/dev/null || true
  apt-get install -y -qq tinygo 2>/dev/null || true
}

check_all() {
  local missing=0
  for t in wat2wasm rustc clang tinygo zig asc; do
    if have "$t"; then
      log "OK   $t -> $(command -v "$t")"
    else
      warn "MISS $t"
      missing=1
    fi
  done
  return "$missing"
}

if [[ "$MODE_SYSTEM" == "1" ]]; then
  install_system_apt
fi

if [[ "$CHECK_ONLY" == "1" ]]; then
  check_all
  exit $?
fi

install_system_apt
install_node_portable || true
install_zig_portable || install_zig_apt_fallback || true
install_tinygo_portable || true
install_wabt_portable || true
install_rustup_user || true
install_asc_npm || true

# clang from apt or already on system — symlink if found
if have clang && [[ ! -e "$HACKME_PREFIX/bin/clang" ]]; then
  link_bin "$(command -v clang)" clang
fi

ENV_OUT="$HACKME_PREFIX/.env.toolchains"
write_env_file "$ENV_OUT"

if [[ "$MODE_DESKTOP" == "1" ]]; then
  cp -f "$ENV_OUT" "$ROOT_DIR/.hackme-toolchains.env"
  log "desktop env: $ROOT_DIR/.hackme-toolchains.env"
  if [[ -d "$ROOT_DIR/logs/desktop" ]]; then
    cp -f "$ENV_OUT" "$ROOT_DIR/logs/desktop/.hackme-toolchains.env"
    log "desktop node env: $ROOT_DIR/logs/desktop/.hackme-toolchains.env"
  fi
fi

if [[ "$(id -u)" -eq 0 ]] && [[ -d /etc/systemd/system ]]; then
  DROPIN="/etc/systemd/system/hackme-node.service.d"
  mkdir -p "$DROPIN"
  cat >"$DROPIN/51-from-code-toolchains.conf" <<EOF
[Service]
EnvironmentFile=${ENV_OUT}
EOF
  log "systemd drop-in: $DROPIN/51-from-code-toolchains.conf"
fi

log "toolchain root: $HACKME_PREFIX"
log "activate: set -a && source $ENV_OUT && set +a"
check_all || warn "some toolchains missing — re-run or install system packages"
log "done"
