#!/usr/bin/env bash
set -euo pipefail

# Generate per-worker env files with unique signer seeds.
#
# Example:
#   WORKERS_CSV="rig-01,rig-02,rig-03" \
#   COORD_URL=http://203.0.113.10:18081 \
#   COORD_TOKEN=... \
#   bash scripts/ops/prepare_worker_fleet_envs.sh

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "[fleet-envs] missing command: $1" >&2
    exit 1
  }
}

require_cmd go
require_cmd jq
require_cmd python3

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

COORD_URL="${COORD_URL:-http://127.0.0.1:18081}"
COORD_TOKEN="${COORD_TOKEN:-${COORD_ADMIN_TOKEN:-${ADMIN_TOKEN:-}}}"
WORKERS_CSV="${WORKERS_CSV:-}"
WORKERS_FILE="${WORKERS_FILE:-}"
OUT_DIR="${OUT_DIR:-${ROOT_DIR}/dist/worker-fleet/$(date +%Y%m%dT%H%M%S)}"
BATCH_SIZE="${BATCH_SIZE:-4194304}"
GPU_CHUNK="${GPU_CHUNK:-4194304}"
SEARCH_TIMEOUT_MS="${SEARCH_TIMEOUT_MS:-2500}"

if [[ -z "$COORD_TOKEN" ]]; then
  echo "[fleet-envs] COORD_TOKEN is required" >&2
  exit 1
fi
if [[ -z "$WORKERS_CSV" && -z "$WORKERS_FILE" ]]; then
  echo "[fleet-envs] set WORKERS_CSV or WORKERS_FILE" >&2
  exit 2
fi
if [[ -n "$WORKERS_FILE" && ! -f "$WORKERS_FILE" ]]; then
  echo "[fleet-envs] WORKERS_FILE not found: $WORKERS_FILE" >&2
  exit 3
fi

mkdir -p "$OUT_DIR"

workers_tmp="$(mktemp)"
if [[ -n "$WORKERS_CSV" ]]; then
  python3 - "$WORKERS_CSV" <<'PY' > "$workers_tmp"
import sys
parts = [p.strip() for p in sys.argv[1].split(",")]
seen = set()
for p in parts:
    if not p or p in seen:
        continue
    seen.add(p)
    print(p)
PY
fi
if [[ -n "$WORKERS_FILE" ]]; then
  awk 'NF {print $1}' "$WORKERS_FILE" >> "$workers_tmp"
fi

mapfile -t WORKERS < <(awk '!seen[$0]++' "$workers_tmp")
rm -f "$workers_tmp"

if [[ "${#WORKERS[@]}" -eq 0 ]]; then
  echo "[fleet-envs] no worker ids resolved" >&2
  exit 4
fi

manifest="${OUT_DIR}/worker_fleet_manifest.csv"
echo "worker_id,miner_address,env_file" > "$manifest"

for wid in "${WORKERS[@]}"; do
  meta="$(go run ./cmd/minersign -gen-seed)"
  seed="$(printf '%s' "$meta" | jq -r '.HACKME_MINER_ED25519_SEED_HEX // ""')"
  addr="$(printf '%s' "$meta" | jq -r '.miner_address_from_pubkey // ""')"
  if [[ -z "$seed" || -z "$addr" ]]; then
    echo "[fleet-envs] failed to generate seed for ${wid}" >&2
    exit 5
  fi
  env_file="${OUT_DIR}/${wid}.env"
  cat > "$env_file" <<EOF
COORD_URL=${COORD_URL}
COORD_TOKEN=${COORD_TOKEN}
WORKER_ID=${wid}
HACKME_MINER_ED25519_SEED_HEX=${seed}

# Optional tuning:
BATCH_SIZE=${BATCH_SIZE}
GPU_CHUNK=${GPU_CHUNK}
SEARCH_TIMEOUT_MS=${SEARCH_TIMEOUT_MS}

# Optional GPU selection:
# HACKME_GPU_BACKEND=auto
# HACKME_GPU_DEVICE=
# HACKME_GPU_DISABLE=0
EOF
  chmod 600 "$env_file"
  echo "${wid},${addr},${env_file}" >> "$manifest"
done

cat > "${OUT_DIR}/README.txt" <<EOF
Worker fleet env bundle generated by prepare_worker_fleet_envs.sh

Files:
- one <worker_id>.env per worker
- worker_fleet_manifest.csv (worker_id -> payout address)

Deploy on each worker host:
1) Copy corresponding env file to /opt/hackme/.env.worker
2) sudo HACKME_ROOT=/opt/hackme ENV_FILE=/opt/hackme/.env.worker bash /opt/hackme/scripts/ops/setup_worker_autostart_service.sh
3) sudo systemctl restart hackme-workerpoh.service
4) journalctl -u hackme-workerpoh.service -f

Security:
- Treat this directory as secret (contains coordinator token + private signer seeds).
EOF

echo "[fleet-envs] generated ${#WORKERS[@]} worker env files"
echo "[fleet-envs] out=${OUT_DIR}"
echo "[fleet-envs] manifest=${manifest}"
