#ifndef LIBXML2_FUZZ_CONFIG_H
#define LIBXML2_FUZZ_CONFIG_H
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_FCNTL_H 1
#define HAVE_DLOPEN 1
#define HAVE_FUNC_ATTRIBUTE_DESTRUCTOR 1
#define XML_SYSCONFDIR "/etc"
#endif
