# Allow mining worker realtime scheduling and high priority I/O.
*               soft    rtprio          99
*               hard    rtprio          99
*               soft    nice            -20
*               hard    nice            -20
root            soft    memlock         unlimited
root            hard    memlock         unlimited
